Support Chrome's UNORDERED_NODE_ITERATOR_TYPE
When chrome's XPath evaluate() method is asked for an ORDERED_NODE_SNAPSHOT_TYPE
it can return an empty UNORDERED_NODE_ITERATOR_TYPE.  This throws an error when
`snapshotLength` is called on it:

             TypeError: Failed to read the 'snapshotLength' property from 'XPathResult': The result type is not a snapshot.

On the other hand, there are other types which will throw a similar error if
`iterateNext()` is called on them.